<?php

namespace Iti\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * this function used to get latest posts
     * @author ahmed
     * use BlogController:index
     * @param integer $limit
     */
    public function getLatestPosts($limit){
        $query = $this->getEntityManager()->createQuery('
            SELECT p
            FROM ItiBlogBundle:Post p
            order by p.createdAt desc
            ')->setMaxResults($limit);
        return $query->getResult();
    }
}
