blog_homepage:
    pattern:  /
    defaults: { _controller: ItiBlogBundle:Blog:index }
    
about_us:
    pattern:  /about
    defaults: { _controller: ItiBlogBundle:Blog:aboutUs }    
    
ItiBlogBundle_post:
        resource: "@ItiBlogBundle/Resources/config/routing/post.yml"
        prefix:   /post    
