parameters:
#    iti_blog.example.class: Iti\BlogBundle\Example

services:
#    iti_blog.example:
#        class: %iti_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
